/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAddressDialog: typeof import('./components/userCenter/AddAddressDialog.vue')['default']
    CommentCard: typeof import('./components/restaurantPage/CommentCard.vue')['default']
    CommentDialog: typeof import('./components/userCenter/CommentDialog.vue')['default']
    CompletedOrderItem: typeof import('./components/userCenter/CompletedOrderItem.vue')['default']
    DeliveringOrderItem: typeof import('./components/userCenter/DeliveringOrderItem.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HoverArea: typeof import('./components/HoverArea.vue')['default']
    LoadMoreInView: typeof import('./components/LoadMoreInView.vue')['default']
    LoginPanel: typeof import('./components/loginPage/LoginPanel.vue')['default']
    MenuCard: typeof import('./components/restaurantCenter/MenuCard.vue')['default']
    MessageCard: typeof import('./components/homePage/MessageCard.vue')['default']
    OrderCard: typeof import('./components/deliveryPage/OrderCard.vue')['default']
    OrderDialog: typeof import('./components/deliveryPage/OrderDialog.vue')['default']
    RegisterPanel: typeof import('./components/loginPage/RegisterPanel.vue')['default']
    RestaurantCard: typeof import('./components/homePage/RestaurantCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingDialog: typeof import('./components/restaurantPage/ShoppingDialog.vue')['default']
    TopNav: typeof import('./components/homePage/TopNav.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
